### ISSUE TITLE
Registration and login can be implemented with serializers with less manual data processing

### ISSUE THREAD

**Issue by stl-pavelsushko** [mdulchevskiy/course_platform_api#3]

**Comment by stl-pavelsushko** [comment]
Here https://github.com/mdulchevskiy/course_platform_api/blob/e21c8936341d76caea8558fe8fcf34de527f6ffc/course_api/views/view_login.py#L23
You unpack data manually:
```
username = self.request.data.get("username")
password = self.request.data.get("password")
```
Which will you could also do with using Serializer and it would help you to provide additional validations on fields

**Comment by mdulchevskiy** [comment]
One of the fields in the serializer is unique, so using this serializer other than in registration will cause an unique error. It seems impossible to remove dynamically validation for uniqueness, but other elegant solutions take a lot of time. In the future I will solve this problem, but now i can only make code worse.
